//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Feedback
    {
        public int SNO { get; set; }
        public string UserId { get; set; }

      
        public string Name { get; set; }

      
        public string Type { get; set; }

        public string EnquiryOn { get; set; }

        public string Email { get; set; }

        public string Contact { get; set; }

        public string Description { get; set; }
    }
}
